### ISSUE TITLE
请问，RemNote缩少到一半屏幕时，侧栏能不能也改为触边弹出？

### ISSUE THREAD

**Issue by Orisik** [yoyooyooo/remnote-theme#1]

**Comment by yoyooyooo** [comment]
这个用 css 做不到，屏幕大的时候rn的展开侧边栏的按钮自带 hover 时弹出，所以改个css就行了。
屏幕小的时候固定在顶部，并且改成了点击才能触发，所以改css没用。

> 不过可以改成触边后原地点击打开侧边栏，总比找图标方便点，已经改了，你试试。

**Comment by Orisik** [comment]
> 这个用 css 做不到，屏幕大的时候rn的展开侧边栏的按钮自带 hover 时弹出，所以改个css就行了。 屏幕小的时候固定在顶部，并且改成了点击才能触发，所以改css没用。
> 
> > 不过可以改成触边后原地点击打开侧边栏，总比找图标方便点，已经改了，你试试。

半屏时触边好像没反应

**Comment by yoyooyooo** [comment]
> > 这个用 css 做不到，屏幕大的时候rn的展开侧边栏的按钮自带 hover 时弹出，所以改个css就行了。 屏幕小的时候固定在顶部，并且改成了点击才能触发，所以改css没用。
> > > 不过可以改成触边后原地点击打开侧边栏，总比找图标方便点，已经改了，你试试。
> 
> 半屏时触边好像没反应

是没反应，，我说了，rn把半屏的触发改成点击了，改 css 没办法改变触发行为。半屏时得点击

**Comment by yoyooyooo** [comment]
close
